# Generated by Django 6.0.3 on 2026-05-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_customuser_managers_profile_avatar'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='answerlike',
            index=models.Index(fields=['user', 'answer'], name='questions_a_user_id_d68a36_idx'),
        ),
        migrations.AddIndex(
            model_name='questionlike',
            index=models.Index(fields=['user', 'question'], name='questions_q_user_id_121b98_idx'),
        ),
        migrations.AddConstraint(
            model_name='answerlike',
            constraint=models.UniqueConstraint(fields=('user', 'answer'), name='unique_answer_like'),
        ),
        migrations.AddConstraint(
            model_name='questionlike',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='unique_question_like'),
        ),
    ]
